#! /bin/env python3
import sys
import argparse

import traceon.geometry as G
import traceon.solver as solver

parser = argparse.ArgumentParser(prog='traceon-solve-geometry', description='Solve for the electrostatic potential of the given geometries and save the solutions in cache')
parser.add_argument('geometry', nargs='+', help='Geometry file')
parser.add_argument('--recompute', action='store_true', help='Recompute solutions already in cache')
args = parser.parse_args()

for filename in args.geometry:
    geom = G.Geometry.read(filename)
    
    electrodes = geom.get_electrodes()
     
    for e in electrodes:
        if e == 'ground':
            continue

        voltages = dict((el, 0.0 if el != e else 1.0) for el in electrodes)
         
        if not args.recompute and solver.solution_exists_in_cache(geom, **voltages):
            print('Not solving because solution already exists in cache')
            continue
         
        print(filename)
         
        print('Solving with voltages: ', voltages)
        solver.field_function_derivs(geom, recompute=True, **voltages)



