#! /bin/env python3
import sys

import traceon.geometry as G
import traceon.solver as solver

for filename in sys.argv[1:]:
    geom = G.Geometry.read(filename)
    mesh = geom.mesh
    
    electrodes = geom.get_electrodes()
     
    for e in electrodes:
        if e == 'ground':
            continue

        voltages = dict((el, 0.0 if el != e else 1.0) for el in electrodes)
         
        if solver.solution_exists_in_cache(mesh, **voltages):
            print('Not solving because solution already exists in cache')
            continue
         
        print(filename)
         
        print('Solving with voltages: ', voltages)
        solver.field_function_derivs(mesh, recompute=True, **voltages)



