---
name: Type Checking

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install scipy-stubs vedo numpy scipy meshio mypy pyright
        
      - name: Run mypy
        run: python3 -m mypy voltrace

      - name: Run pyright
        run: pyright
